thrift: add formatted descriptions and messages to task tags, add latestTaskTag to top-level configurable objects
thrift:
    Add EValidationError: has type, formattedMessage, messageParameters, errorInField
    Add latestTaskTag to all objects that have assosicated task tags
Forte:
    Exception: add EXCEPTION_PARAM_SUBCLASS(PARENT, NAME, DESC, PARAM_TYPES)
        DESC is a format literal containing only %s tokens
        PARAMS_TYPES is in format (type1)(type2)...
    Exception: add virtual method const std::string &GetFormattedDescription()
    Exception: add virtual method std::string GetFormattedDescriptionAsObjCStyle()
    Exception: add virtual method void GetParametersAsStrings(std::vector<std::string> &result)
    FString: add ObjectiveC format method OFormat(format, parameters);
    FString: add ObjectiveC format constructor FString(const FStringFO ,format, parameters);
    DbRow: add UnFetch() method: moves iterator back
db: configuration_schema:
    DbTasks: Add formattedMessage (string), messageParameters (blob)
scaled:
    refactor all scaled read calls to utilize TaskManager::UpdateTaskStatusForObjects
    TaskManager:
        If Task fails (Exception thrown): write obj-c style string/parameters into DbTask
        Move DbTask Creation to TaskManager, so defaults can be set
        Refactor GetNewTaskTag to support parameters
        Add templated method UpdateTaskStatusForObjects that takes a vector of
            objects and fils in their latestTaskTag
    ADSManager:
        Use EValidationError
        If Callbacks tasks fail: throw proper exceptions
        fix invalid guid being used for join/leaves
    SCSIManager:
        Use EValidationError
    ShareManager
        Use EvalidationError
    ScaledExceptions: add macros for validation exceptions, so that
        a thrift call will rethrow the naked member mThriftException
scqad:
    ADSConfigSetup.case: Validate Exceptions for rollouts

Change-Id: I3f559297091d66478d7c1b62dd93ba2bf07431d2
Reviewed-on: http://gerrit.lab.local:8080/395
Tested-by: build
Reviewed-by: Phil White <pwhite@scalecomputing.com>