[STOR-3755] Use virtlockd instead of sanlock
This is a large change removing sanlock from the product and adding
virtlockd instead. The difference between the two lock managers is that
sanlock uses the paxos algorithm utilizing the clustered filesystem as a
communication layer. Thus it is very dependent on responsiveness of the
filesystem.  Virtlockd instead uses posix locking.

This change helps improve libvirt responsiveness, startup times, and the
failover time.

Changes:
General: Search and Replace sanlock with virtlockd
rpmlists: Upgrade to libvirt 1.0.0.1-sc01
 - Upgrade was required due to complexity of backporting the virtlockd
   patch.

VirtCollector: Remove lockspace missing support
Conditions: remove checks for cv.daemons.libvirtd.lockspace.missing
VirtManager: handle new lockspace errors

scqad:
  modify tags to virtlockd.
  VMCreateAndDelete: Disable lockspace test: @todo: enable again

VirtError: Handle new error codes

Upgrade Patch 1400: Remove sanlock

Change-Id: I522e4870797d143a8198ec775f5a948d942756d4
Reviewed-on: http://gerrit.lab.local:8080/2786
Tested-by: build
Smoketests: build
Reviewed-by: Asad Saeed <asaeed@scalecomputing.com>
Reviewed-by: Hank Hsieh <hhsieh@scalecomputing.com>
Reviewed-by: Nate Hardt <nate@scalecomputing.com>
Reviewed-on: http://gerrit.lab.local:8080/2826
Smoketests: Nate Hardt <nate@scalecomputing.com>
Tested-by: Nate Hardt <nate@scalecomputing.com>